blank_issues_enabled: false
contact_links:
  - name: Adventurer's Cookbook Community Support
    url: https://github.com/bayhasoft/adventurers-cookbook/discussions/categories/how-do-i
    about: Please ask and answer questions here.
  - name: Adventurer's Cookbook Bug Bash
    url: https://github.com/bayhasoft/adventurers-cookbook/discussions/categories/bug-reports
    about: report bugs here
